### ISSUE TITLE
Geoserver: 0.18 doesn't show up as datasource. 0.16 does.

### ISSUE THREAD

**Issue by MobiusF** [neo4j-contrib/spatial#260]
Has anyone tested Geoserver with 0.16 or 0.18 libs?
Is there a chance someone can do this on short term?

**Comment by MobiusF** [comment]
exception in Geoserver (2.3.2, geotools 9.2) , using 0.16 spatial lib and neo4j 3.03
Caused by: org.neo4j.kernel.impl.core.ThreadToStatementContextBridge$BridgeNotInTransactionException: The requested operation cannot
 be performed, because it has to be performed in a transaction. Ensure you are wrapping your operation in the appropriate transactio
n boilerplate and try again.
        at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.assertInUnterminatedTransaction(ThreadToStatementContextBridge.
java:72)
        at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getTopLevelTransactionBoundToThisThread(ThreadToStatementContex
tBridge.java:105)
        at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getKernelTransactionBoundToThisThread(ThreadToStatementContextB
ridge.java:113)
        at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.get(ThreadToStatementContextBridge.java:65)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.currentStatement(ClassicCoreSPI.java:205)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade$$Lambda$43/23848913.get(Unknown Source)
        at org.neo4j.kernel.impl.coreapi.StandardNodeActions.statement(StandardNodeActions.java:56)
        at org.neo4j.kernel.impl.core.NodeProxy.hasProperty(NodeProxy.java:492)
        at org.neo4j.gis.spatial.rtree.RTreeIndex.isEmpty(RTreeIndex.java:241)
        at org.geotools.data.neo4j.Neo4jSpatialDataStore.getTypeNames(Neo4jSpatialDataStore.java:107)
        at org.vfny.geoserver.util.DataStoreUtils.getDataAccess(DataStoreUtils.java:114)
        at org.geoserver.catalog.ResourcePool.getDataStore(ResourcePool.java:539)

**Comment by craigtaverner** [comment]
That error looks like a missing transaction around read operations. That would be a problem for all versions of Neo4j since 2.0 when they made read operations compulsory. I've taken a look, and made a possible fix at https://github.com/neo4j-contrib/spatial/commit/7a7dedce2f28fec0d113e528eab91ba3de1c8403

I'm busy publishing a version 0.15.2 with this fix which you can try out and see if it works for you. I have not tested in GeoServer itself, but was able to reproduce three related issues in Neo4jSpatialDataStore which I fixed, so there is a good chance this does the trick.

**Comment by craigtaverner** [comment]
The above fix was related to, but not the cause of the error you had, since I was fixing issues back in 0.15. It seems that there was an additional issue happening only in newer neo4j 3.0.x (x>1) that required an additional transaction. I've made a fix here: https://github.com/neo4j-contrib/spatial/commit/3925b34ed02d3e53b327423f6f8d3f05ad673e49

I'll publish a new 0.19-neo4j-3.0.3 with this fix for you to try.

**Comment by craigtaverner** [comment]
0.19 is now available at https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.19-neo4j-3.0.3/neo4j-spatial-0.19-neo4j-3.0.3-server-plugin.jar?raw=true

**Comment by MobiusF** [comment]
Craig,
Thanks for responding so quick. You seem to have found some issues I wasn't aware of yet.
Unfortunaly 0.19 still won't reveal itself to geoserver as a potential datastore.
It's een some years since I did some serious programming and it wasn't Java, but I had a look at it.
It seems related to the geotools DataStoreFinder class and Neo4jSpatialDataStoreFactory implementing DataStoreFactorySpi. But I just can't put my finger on it.
I'll be of grid for the next 3 weeks, after that I will look into it again.

Thanks again,

BR

**Comment by craigtaverner** [comment]
I'm trying to compile geoserver 2.3.2 locally to test against, but having trouble with it, seemingly because many dependencies are no longer available. I'm considering investigating the level of effort to upgrade Neo4j Spatial to a newer GeoTools (and therefor newer GeoServer). I wonder what people would prefer to see.

The latest stable GeoServer is 2.9.0, using GeoTools 15.0.
Supported maintenance release if 2.8.4, using GeoTools 14.4.

**Comment by mprins** [comment]
Note: geotools15 / geoserver 2.9 require java 8

**Comment by craigtaverner** [comment]
Neo4j 3.0 was compiled with Java 8 and uses Java 8 features in the code. I compile Neo4j Spatial with Java 8, but set the java language to 7 for now.

Anyway, I just tried porting to GeoTools 14.4 (for GeoServer 2.8.4), and I needed to make a few small code changes, but all current tests pass (although I fear our test coverage around the DataStore side of things is very weak). I'm smoke testing a new Neo4j Spatial 0.20 release on Neo4j 3.0.3 and procedures seem to work as before.

Perhaps you would be interested in trying the new 0.20-neo4j-3.0.3 version of Neo4j Spatial in GeoServer?

**Comment by MobiusF** [comment]
Craig,

If I try to create a new store using 0.20, neo4j isn't listed. I verified again using 0.16. It is listed, but using it indeed complains about a missing transaction. You might have solved the later problem, but if I can't choose neo4j as datasource....

BR

**Comment by craigtaverner** [comment]
Are you trying 0.20 on GeoServer 2.8.4 or 2.3.2? I built it for GeoTools 14.4, so it should only work on GeoServer 2.8.4.

**Comment by MobiusF** [comment]
2.8.4 of course.
Found it. For some reason the web-inf/services/org.geotools.data.DataStoreFactorySpi in the 0.20 jar says:
org.geotools.data.shapefile.ShapefileDataStoreFactory
org.geotools.data.shapefile.ShapefileDirectoryFactory
Haven't the foggiest why this happens. I copied the 0.16 correct service directly into the 0.20 jar and Neo4j shows up in the datasources selection screen.
Correct contents of the services file:
org.geotools.data.neo4j.Neo4jSpatialDataStoreFactory

**Comment by MobiusF** [comment]
There is still someting not in a transaction. When I make a neo4j datastore, the layers comes up at first, but after that i get:
Caused by: org.neo4j.kernel.impl.core.ThreadToStatementContextBridge$BridgeNotInTransactionException: The requested operation cannot
 be performed, because it has to be performed in a transaction. Ensure you are wrapping your operation in the appropriate transactio
n boilerplate and try again.
        at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.assertInUnterminatedTransaction(ThreadToStatementContextBridge.
java:72)
        at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getTopLevelTransactionBoundToThisThread(ThreadToStatementContex
tBridge.java:105)
        at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getKernelTransactionBoundToThisThread(ThreadToStatementContextB
ridge.java:113)
        at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.get(ThreadToStatementContextBridge.java:65)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.currentStatement(ClassicCoreSPI.java:205)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade$$Lambda$46/18692383.get(Unknown Source)
        at org.neo4j.kernel.impl.coreapi.StandardNodeActions.statement(StandardNodeActions.java:56)
        at org.neo4j.kernel.impl.core.NodeProxy.hasProperty(NodeProxy.java:492)
        at org.neo4j.gis.spatial.DefaultLayer.getGeometryType(DefaultLayer.java:131)
        at org.geotools.data.neo4j.Neo4jFeatureBuilder.getTypeFromLayer(Neo4jFeatureBuilder.java:91)
        at org.geotools.data.neo4j.Neo4jSpatialDataStore.getSchema(Neo4jSpatialDataStore.java:132)
        at org.geotools.data.neo4j.Neo4jSpatialDataStore.getFeatureSource(Neo4jSpatialDataStore.java:147)
        at org.geotools.data.AbstractDataStore.getFeatureSource(AbstractDataStore.java:600)
        at org.geotools.data.AbstractDataStore.getFeatureSource(AbstractDataStore.java:38)
        at org.geoserver.catalog.CatalogBuilder.buildFeatureType(CatalogBuilder.java:329)
        at org.geoserver.web.data.layer.NewLayerPage.buildLayerInfo(NewLayerPage.java:349)

**Comment by MobiusF** [comment]
added transactions in Neo4jSpatialDataStore:

public SimpleFeatureType getSchema(String typeName) throws IOException {
        SimpleFeatureType result = simpleFeatureTypeIndex.get(typeName);
        if (result == null) {
            Layer layer = spatialDatabase.getLayer(typeName);
            if (layer == null) {
                throw new IOException("Layer not found: " + typeName);
            }
            try (Transaction tx = database.beginTx()) {
            	result = Neo4jFeatureBuilder.getTypeFromLayer(layer);
            	simpleFeatureTypeIndex.put(typeName, result);
            	tx.success();
			}
        }
        return result;
    }

public ReferencedEnvelope getBounds(String typeName) {
    	ReferencedEnvelope result = boundsIndex.get(typeName);
		if (result == null) {
			Layer layer = spatialDatabase.getLayer(typeName);
			if (layer != null) {
				try (Transaction tx = database.beginTx()) {
					Envelope bbox = Utilities.fromNeo4jToJts(layer.getIndex().getBoundingBox());
					result = convertEnvelopeToRefEnvelope(typeName, bbox);
					boundsIndex.put(typeName, result);
				tx.success();
				}
			}
		}
		return result;
    }

private CoordinateReferenceSystem getCRS(String typeName) {
    	CoordinateReferenceSystem result = crsIndex.get(typeName);
        if (result == null) {
            Layer layer = spatialDatabase.getLayer(typeName);
            try (Transaction tx = database.beginTx()) {
            	result = layer.getCoordinateReferenceSystem();
            	crsIndex.put(typeName, result);
            	tx.success();
            }
        }
    	
    	return result;
    }

**Comment by MobiusF** [comment]
With these alterations, using geoserver 2.8.4, I can configure a neo4j datastore, get it's layer, ask for the max BB and preview it in openlayers.

btw. Have you seen the deprecation warning for AbstractDataStoreFactory !!

**Comment by craigtaverner** [comment]
Since you've already made the code changes, could you consider sending a pull-request? (and signing the CLA if not already done). That way you also get credit for this work!

**Comment by MobiusF** [comment]
Craig,

I'm not yet comfortable with git and I might not ever be. Please do the honours for me!
Besides I don't know how the erreanous services file came to be or how the correct one can be generated.

And W*F is a CLA

BR

**Comment by craigtaverner** [comment]
The CLA is described here - https://neo4j.com/developer/cla/

Making a PR in github is usually pretty straightforward. There are lots of tutorials. I assume you already forked this repo and used 'git clone' to get it locally so you could see and edit the code. What you would do now is commit your changes, push them to a new branch on github, go to that branch on github and click the button it offers to make a pull request. If you did not fork the repo first, you will not be able to push, but we can fix that easily too. If you have trouble, consider emailing me directly and we can setup some kind of chat to walk you through it.

**Comment by MobiusF** [comment]
hint: gt-shapefile-X.Y.jar contains the 'faulty' services file, both 9.2 and 14.4 versions. Somehow the merging of the services files isn't working.

**Comment by MobiusF** [comment]
"The purpose of the Neo4j Contributor License Agreement is to protect the integrity of the code base" 
Ergo: you don't want me to have a CLA, trust me.....

I just created 3 transaction wrappers. that's 6 times ctrl-c ctrl-v. Please do them yourself.

And it's not likely I will contribute more than this. I just got stuck and had some time on my hands.

**Comment by craigtaverner** [comment]
I pushed this commit. Could you review it? https://github.com/neo4j-contrib/spatial/commit/286593b062a35010df7e53f25a453535d4f0fa3d

I've not begun to investigate why the jar has the wrong services.

**Comment by MobiusF** [comment]
Craig,

0.21 is fine, once the services file is copied.

**Comment by MobiusF** [comment]
To merge the services files:
Add to pom:
property
<maven-assembly-plugin.version>2.5.4</maven-assembly-plugin.version>
and version to the plugin:
<artifactId>maven-assembly-plugin</artifactId>
<version>${maven-assembly-plugin.version}</version>
then add to server-plugin.xml under <assembly> 
  <containerDescriptorHandlers>
    <containerDescriptorHandler>
        <handlerName>metaInf-services</handlerName>
    </containerDescriptorHandler>
  </containerDescriptorHandlers>
 
This will merge the services file:
org.geotools.data.shapefile.ShapefileDataStoreFactory
org.geotools.data.shapefile.ShapefileDirectoryFactory
org.geotools.data.neo4j.Neo4jSpatialDataStoreFactory

Works fine.

**Comment by MobiusF** [comment]
hmmm. xml tags disappear.
`<maven-assembly-plugin.version>2.5.4</maven-assembly-plugin.version>`

**Comment by MobiusF** [comment]
better.
pom.xml:
`<maven-assembly-plugin.version>2.5.4</maven-assembly-plugin.version>`

and 

`<artifactId>maven-assembly-plugin</artifactId>
 <version>${maven-assembly-plugin.version}</version>`

server-plugin.xml
`  <containerDescriptorHandlers>
    <containerDescriptorHandler>
        <handlerName>metaInf-services</handlerName>
    </containerDescriptorHandler>
  </containerDescriptorHandlers>`

**Comment by craigtaverner** [comment]
I've made those changes and you can download a 0.22-neo4j-3.0.4 version here: https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.22-neo4j-3.0.4/neo4j-spatial-0.22-neo4j-3.0.4-server-plugin.jar?raw=true

I also noted that the file META-INF/services/org.geotools.data.DataStoreFactorySpi now contains the lines:

```
org.geotools.data.shapefile.ShapefileDataStoreFactory
org.geotools.data.shapefile.ShapefileDirectoryFactory
org.geotools.data.neo4j.Neo4jSpatialDataStoreFactory
```

Let me know if this works for you.

**Comment by MobiusF** [comment]
Criag,

This one is great. Works 'out of the box'
So I'll close this issue.....and open another one....

Thx,

BR
